### ISSUE TITLE
The example HTML file is empty

### ISSUE THREAD

**Issue by pnavato** [mezzoblue/csszengarden.com#121]
When I click on "Download the example HTML FILE" it opens an empty page at https://www.csszengarden.com/examples/index

Also the link to http://www.mezzoblue.com/ in the footer should be changed because that site does not exist anymore.

**Comment by Lyumih** [comment]
![IMAGE 2023-06-13 08:31:44](https://github.com/mezzoblue/csszengarden.com/assets/32732179/7718e63c-b89b-4050-b599-9bce7b9ab23b) 

HTTPS -> HTTP canceled
